SkillsFundingAgency/dfc-servicetaxonomy-editor

.gitignore, DFC.ServiceTaxonomy.Editor.Module/Neo4j/Services/NeoGraphDatabase.cs, DFC.ServiceTaxonomy.Editor.sln, DFC.ServiceTaxonomy.Editor/Recipes/Service Taxonomy.recipe.json, DFC.ServiceTaxonomy.Editor/appsettings.json
Adds the previously ignored appsettings.json file
+ minor changes
=> Further initial work

DFC.ServiceTaxonomy.Editor/DFC.ServiceTaxonomy.Editor.csproj, DFC.ServiceTaxonomy.GraphLookup/DFC.ServiceTaxonomy.GraphLookup.csproj, DFC.ServiceTaxonomy.GraphSync/DFC.ServiceTaxonomy.GraphSync.csproj
The Orchard Core packaging issues have been fixed.
Also, as a bonus the delete content item(s) now works.
=> Use latest oc packages again

DFC.ServiceTaxonomy.GraphSync/Activities/SyncToGraphTask.cs, DFC.ServiceTaxonomy.GraphSync/GraphSyncers/BagPartGraphSyncer.cs, DFC.ServiceTaxonomy.GraphSync/GraphSyncers/GraphSyncer.cs, DFC.ServiceTaxonomy.GraphSync/GraphSyncers/IUpsertGraphSyncer.cs, DFC.ServiceTaxonomy.GraphSync/GraphSyncers/Interfaces/IGraphSyncer.cs
- Add Created Date and Last Modified date to properties collection for all nodes
=> - Add Created Date and Last Modified date

DFC.ServiceTaxonomy.GraphSync/GraphSyncers/BagPartGraphSyncer.cs
- Change IGraphSyncer to IUpsertGraphSyncer
=> - Change part dates to check for string empty as well as null

DFC.ServiceTaxonomy.GraphVisualiser/Controllers/VisualiseController.cs, DFC.ServiceTaxonomy.GraphVisualiser/DFC.ServiceTaxonomy.GraphVisualiser.csproj, DFC.ServiceTaxonomy.GraphVisualiser/Models/Configuration/OwlDataGeneratorConfigModel.cs, DFC.ServiceTaxonomy.GraphVisualiser/Models/NodeDataModel.cs, DFC.ServiceTaxonomy.GraphVisualiser/Models/Owl/CheckBox.cs, DFC.ServiceTaxonomy.GraphVisualiser/Models/Owl/Class.cs, DFC.ServiceTaxonomy.GraphVisualiser/Models/Owl/ClassAttribute.cs, DFC.ServiceTaxonomy.GraphVisualiser/Models/Owl/Description.cs, DFC.ServiceTaxonomy.GraphVisualiser/Models/Owl/Filter.cs, DFC.ServiceTaxonomy.GraphVisualiser/Models/Owl/Header.cs, DFC.ServiceTaxonomy.GraphVisualiser/Models/Owl/Modes.cs, DFC.ServiceTaxonomy.GraphVisualiser/Models/Owl/Namespace.cs, DFC.ServiceTaxonomy.GraphVisualiser/Models/Owl/OwlDataModel.cs, DFC.ServiceTaxonomy.GraphVisualiser/Models/Owl/Property.cs, DFC.ServiceTaxonomy.GraphVisualiser/Models/Owl/PropertyAttribute.cs, DFC.ServiceTaxonomy.GraphVisualiser/Models/Owl/Settings.cs, DFC.ServiceTaxonomy.GraphVisualiser/Models/RelationshipDataModel.cs, DFC.ServiceTaxonomy.GraphVisualiser/Queries/GetNodesCypherQuery.cs, DFC.ServiceTaxonomy.GraphVisualiser/Services/IOrchardToOwlGeneratorService.cs, DFC.ServiceTaxonomy.GraphVisualiser/Services/OrchardToOwlGeneratorService.cs, DFC.ServiceTaxonomy.GraphVisualiser/Services/OwlDataGeneratorService.cs
<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
<Nullable>enable</Nullable>
And refactored accordingly
=> Added project properties

DFC.ServiceTaxonomy.Editor/Views/ContentPreview.Button.cshtml, DFC.ServiceTaxonomy.Editor/Views/Contents-Button-Actions.SummaryAdmin.cshtml
Currently, only a partial fix.
=> Fix replaced UI elements

DFC.ServiceTaxonomy.GraphSync/Activities/AuditSyncIssuesTask.cs, DFC.ServiceTaxonomy.GraphSync/Activities/DeleteContentTypeFromGraphTask.cs, DFC.ServiceTaxonomy.GraphSync/Activities/DeleteContentTypeTask.cs, DFC.ServiceTaxonomy.GraphSync/Activities/DeleteFromGraphTask.cs, DFC.ServiceTaxonomy.GraphSync/Activities/SyncToGraphTask.cs, DFC.ServiceTaxonomy.GraphSync/Recipes/Executors/CypherToContentStep.cs, DeveloperNotes.md
(mostly fix for when sync fails on the content page)
=> Fix content page blowing up when sync fails

DFC.ServiceTaxonomy.Editor/Startup.cs
just commenting out breaking code for now. the proper fix can follow :)
=> Fix startup

Resources/AzureDevOps/JobTemplates/deploy-environment.yml
Added workspace clean in deploy-environment.yml
=> NCSD-3266-Add-workspace-clean-dfc-dev-stax-editor-deployment.yml

Resources/AzureDevOps/GitVersion.yml
added mode: Mainline to gitversion to resolve nuget package not getting new versions each build
=> added gitversion mode mainline to version nuget package

Resources/ArmTemplates/parameters.json, Resources/ArmTemplates/template.json, Resources/ArmTemplates/test-parameters.json, Resources/AzureDevOps/VariableTemplates/DevEnvironmentVariables.yml, Resources/AzureDevOps/azure-pipelines.yml
Added event grid app settings.
Amended condition for deploying to dev so it depends on build stage success instead of depending on recently added publish to nuget stage. The publish to nuget stage only runs when deploying master so this resolves not being able to release feature branches to dev
=> Ncsd 3595 add eventgrid settings

DFC.ServiceTaxonomy.GraphSync/Recipes/Executors/CSharpContentStep.cs, DFC.ServiceTaxonomy.GraphSync/Recipes/Executors/ContentNoCacheStep.cs, DFC.ServiceTaxonomy.GraphSync/Recipes/Executors/CypherToContentStep.cs, DeveloperNotes.md
+ try and keep memory below app service mem limits
=> Memory Optimisations

Resources/AzureDevOps/azure-pipelines.yml
-Amended nuget package step to be based on .csproj file rather than .nuspec file.
-Amended nuget package step to specify configuration = 'release'
=> Nuspec update

DFC.ServiceTaxonomy.Events/Models/ContentEvent.cs, DFC.ServiceTaxonomy.Events/Models/ContentEventData.cs
=> - Move WorkflowCorrelationId to Event Data

DFC.ServiceTaxonomy.GraphSync/Views/GraphSyncPart.Edit.cshtml, DeveloperNotes.md
=> DFCC-585 Fix missing id during sync when id not displayed

Resources/AzureDevOps/azure-pipelines.yml
replaced nuget pack with dotnet pack
=> Ncsd 4173 tshoot nuget pack

DFC.ServiceTaxonomy.Events/Extensions/ServiceCollectionExtensions.cs, DFC.ServiceTaxonomy.Events/Services/EventGridContentClient.cs, DFC.ServiceTaxonomy.GraphSync/Activities/AuditSyncIssuesTask.cs, DFC.ServiceTaxonomy.GraphSync/GraphSyncers/DeleteGraphSyncer.cs, DFC.ServiceTaxonomy.GraphSync/GraphSyncers/DeleteTypeGraphSyncer.cs, DFC.ServiceTaxonomy.GraphSync/GraphSyncers/Helpers/ContentFieldsGraphSyncer.cs, DFC.ServiceTaxonomy.GraphSync/GraphSyncers/Items/ContentItemGraphSyncer.cs, DFC.ServiceTaxonomy.GraphSync/GraphSyncers/MergeGraphSyncer.cs, DFC.ServiceTaxonomy.GraphSync/GraphSyncers/ValidateAndRepairGraph.cs, DFC.ServiceTaxonomy.GraphSync/Handlers/Orchestrators/DeleteOrchestrator.cs, DFC.ServiceTaxonomy.GraphSync/Handlers/Orchestrators/Orchestrator.cs, DFC.ServiceTaxonomy.GraphSync/Handlers/Orchestrators/SyncOrchestrator.cs, DFC.ServiceTaxonomy.GraphSync/Recipes/Executors/CSharpContentStep.cs, DFC.ServiceTaxonomy.GraphSync/Recipes/Executors/ContentNoCacheStep.cs, DFC.ServiceTaxonomy.GraphSync/Recipes/Executors/CypherCommandStep.cs, DFC.ServiceTaxonomy.GraphSync/Recipes/Executors/CypherToContentStep.cs, DFC.ServiceTaxonomy.PageLocation/Handlers/DefaultPageLocationsContentHandler.cs, DeveloperNotes.md
=> Improve logging

DFC.ServiceTaxonomy.GraphSync/GraphSyncers/ContentItemVersions/ContentItemVersion.cs, DFC.ServiceTaxonomy.GraphSync/GraphSyncers/ContentItemVersions/EscoContentItemVersion.cs, DFC.ServiceTaxonomy.GraphSync/GraphSyncers/ContentItemVersions/NeutralEventContentItemVersion.cs, DFC.ServiceTaxonomy.GraphSync/GraphSyncers/ContentItemVersions/PreExistingContentItemVersion.cs, DFC.ServiceTaxonomy.GraphSync/GraphSyncers/ContentItemVersions/SuperpositionContentItemVersion.cs, DFC.ServiceTaxonomy.GraphSync/GraphSyncers/Fields/TaxonomyFieldGraphSyncer.cs, DFC.ServiceTaxonomy.GraphSync/GraphSyncers/Helpers/DescribeContentItemHelper.cs, DFC.ServiceTaxonomy.GraphSync/GraphSyncers/Interfaces/ContentItemVersions/IContentItemVersion.cs, DFC.ServiceTaxonomy.GraphSync/GraphSyncers/Parts/TermPartGraphSyncer.cs, DFC.ServiceTaxonomy.GraphSync/GraphSyncers/ValidateAndRepairGraph.cs, DFC.ServiceTaxonomy.GraphSync/GraphSyncers/VisualiseGraphSyncer.cs, DFC.ServiceTaxonomy.GraphSync/Handlers/Orchestrators/SyncOrchestrator.cs, DFC.ServiceTaxonomy.Neo4j/Services/GraphReplicaSet.cs, DeveloperNotes.md
Also:
* Fix visualiser not showing published-only item in preview graph
=> DFCC-1020 Continue validation and repair if an item repair fails

DFC.ServiceTaxonomy.Editor/Recipes/Service Taxonomy.recipe.json, DFC.ServiceTaxonomy.Editor/Recipes/Service Taxonomy2.recipe.json, DFC.ServiceTaxonomy.Editor/appsettings.json
=> Add preexistingnodeuri to recipes and move dysac personality trait to correct recipe

DFC.ServiceTaxonomy.CSharpScriptGlobals.CypherToContent/DFC.ServiceTaxonomy.CSharpScriptGlobals.CypherToContent.csproj, DFC.ServiceTaxonomy.Content/Services/ContentItemsService.cs, DFC.ServiceTaxonomy.Content/Services/Interface/IContentItemsService.cs, DFC.ServiceTaxonomy.ContentPickerPreview/DFC.ServiceTaxonomy.ContentPickerPreview.csproj, DFC.ServiceTaxonomy.CustomFields/DFC.ServiceTaxonomy.CustomFields.csproj, DFC.ServiceTaxonomy.Cypher/DFC.ServiceTaxonomy.Cypher.csproj, DFC.ServiceTaxonomy.Editor/DFC.ServiceTaxonomy.Editor.csproj, DFC.ServiceTaxonomy.Events/DFC.ServiceTaxonomy.Events.csproj, DFC.ServiceTaxonomy.GraphLookup/DFC.ServiceTaxonomy.GraphLookup.csproj, DFC.ServiceTaxonomy.GraphSync/Activities/AuditSyncIssuesTask.cs, DFC.ServiceTaxonomy.GraphSync/AdminMenu.cs, DFC.ServiceTaxonomy.GraphSync/Controllers/GraphSyncController.cs, DFC.ServiceTaxonomy.GraphSync/DFC.ServiceTaxonomy.GraphSync.csproj, DFC.ServiceTaxonomy.GraphSync/GraphSyncers/Helpers/AuditSyncLog.cs, DFC.ServiceTaxonomy.GraphSync/GraphSyncers/Interfaces/IValidateAndRepairGraph.cs, DFC.ServiceTaxonomy.GraphSync/GraphSyncers/ValidateAndRepairGraph.cs, DFC.ServiceTaxonomy.GraphSync/Migrations.cs, DFC.ServiceTaxonomy.GraphSync/Views/GraphSync/TriggerSyncValidation.cshtml, DFC.ServiceTaxonomy.GraphVisualiser/DFC.ServiceTaxonomy.GraphVisualiser.csproj, DFC.ServiceTaxonomy.IntegrationTests/DFC.ServiceTaxonomy.IntegrationTests.csproj, DFC.ServiceTaxonomy.Neo4j/DFC.ServiceTaxonomy.Neo4j.csproj, DFC.ServiceTaxonomy.Theme/DFC.ServiceTaxonomy.Theme.csproj, DFC.ServiceTaxonomy.UnitTests/DFC.ServiceTaxonomy.UnitTests.csproj
Split validate graph and repair admin menu into
* Validate and Repair All Items
* Validate and Repair Recent Items
Change overnight sync validation to validate **all** items.
=> DFCC-973 Introduce validation scope

DFC.ServiceTaxonomy.Content/DFC.ServiceTaxonomy.Content.csproj, DFC.ServiceTaxonomy.Content/Views/ContentsMeta_SummaryAdmin.cshtml, DFC.ServiceTaxonomy.Content/Views/_ViewImports.cshtml
=> Added published date to all published content items in Manage Content view

DFC.ServiceTaxonomy.GraphSync/Handlers/EventGridPublishingHandler.cs, DFC.ServiceTaxonomy.GraphSync/Handlers/GraphSyncContentHandler.cs, DFC.ServiceTaxonomy.GraphSync/Handlers/Interfaces/IContentOrchestrationHandler.cs, DFC.ServiceTaxonomy.GraphSync/Notifications/GraphSyncNotifier.cs, DFC.ServiceTaxonomy.GraphSync/Orchestrators/DeleteOrchestrator.cs, DFC.ServiceTaxonomy.GraphSync/Orchestrators/Interfaces/ISyncOrchestrator.cs, DFC.ServiceTaxonomy.GraphSync/Orchestrators/Orchestrator.cs, DFC.ServiceTaxonomy.GraphSync/Orchestrators/SyncOrchestrator.cs, DFC.ServiceTaxonomy.GraphSync/Services/SyncOperation.cs, DFC.ServiceTaxonomy.UnitTests/GraphSync/Orchestrators/SyncOrchestratorTests/SyncOrchestrator_PublishTests.cs, DFC.ServiceTaxonomy.UnitTests/GraphSync/Orchestrators/SyncOrchestratorTests/SyncOrchestrator_RestoreTests.cs, DFC.ServiceTaxonomy.UnitTests/GraphSync/Orchestrators/SyncOrchestratorTests/SyncOrchestrator_UpdateTests.cs, DFC.ServiceTaxonomy.UnitTests/GraphSync/Orchestrators/SyncOrchestratorTestsBase.cs, GetJobProfiles/Models/Recipe/Parts/PageLocationPart.cs
Also
* don't show info notifications when there's an error notification (info notifications are used where they should really be success notifications)
=> DFCC-1536 Sync on restore

DFC.ServiceTaxonomy.Editor/Recipes/Service Taxonomy2.recipe.json
Makes job category visualisation useful, rather than a hot mess.
=> DFCC-1543 Limit category visualisation to 1 hop

DFC.ServiceTaxonomy.Editor/Recipes/00_Pages_SharedContent.recipe.json
Added spaces either side of the service opening hour '-'
=> Updated Speak to an adviser markup

DFC.ServiceTaxonomy.IntegrationTests/Helpers/GraphClusterIntegrationTest.cs, DFC.ServiceTaxonomy.IntegrationTests/Helpers/IntegrationTestLogId.cs, DFC.ServiceTaxonomy.Neo4j/Commands/Implementation/NodeWithOutgoingRelationshipsCommand.cs
Build server doesn't support c#9 yet
=> Fix build on server

DFC.ServiceTaxonomy.Editor/Recipes/ft2-82-content-approval-module.recipe.json
Added required default permissions to access admin panel
Tweaked role permissions to allow viewing content for review
=> FT2-125 fixing role permissions for custom content approval roles

DFC.ServiceTaxonomy.Editor/Recipes/ft2-82-content-approval-module.recipe.json
Removing Manage Roles permission from content admin role
=> FT2-129 fixing content admin role

DFC.ServiceTaxonomy.ContentApproval/Controllers/ContentApprovalController.cs, DFC.ServiceTaxonomy.ContentApproval/Permissions/CanPerformReviewPermissions.cs
Change of nofication message
Fixing permission description
Fixing decision statement
=> FT2-86 minor changes to PR

DFC.ServiceTaxonomy.ContentApproval/Drivers/ContentApprovalPartDisplayDriver.cs, DFC.ServiceTaxonomy.ContentApproval/ViewModels/ContentApprovalPartViewModel.cs
Comment validation will both check for a comment and ensure that is different to previous comment.
=> FT2-265 amendment to comment validation

DFC.ServiceTaxonomy.Editor.sln, DFC.ServiceTaxonomy.Editor/Constants/Common.cs, DFC.ServiceTaxonomy.Editor/Security/ApplicationBuilderExtensions.cs, DFC.ServiceTaxonomy.Editor/Startup.cs, DFC.ServiceTaxonomy.Editor/appsettings.Development_template.json, DFC.ServiceTaxonomy.Editor/appsettings.json, MediaContent.md
- Updated CSP to all Images
- Updated config for Digital Assets CDN
- Updated Media Config for CDN location
- Add new doc file for media settings
=> Ft2 263 add cdn location to media tags

DFC.ServiceTaxonomy.Editor/appsettings.json, MediaContent.md
Updated config file to match with DevOps pipeline config.
=> FT2-289 Update config to match with devops pipeline config

DFC.ServiceTaxonomy.Editor/Startup.cs
Minor change to trim trailing occurrence of '/' from cnd base url.
=> FT2-261 Minor change to trim trailing occurrences of '/' from cdn url

DFC.ServiceTaxonomy.ContentApproval/Migrations.cs, DFC.ServiceTaxonomy.ContentApproval/Migrations/stax-content-approval-amendment-02.recipe.json
New recipe to update content approval user roles with dashboard access
Migrations updated to run new recipe and update create
=> FT2-281 fixing dashboard access

DFC.ServiceTaxonomy.Theme/wwwroot/Scripts/trumbowyg.gds.js
Added code to set query params for Youtube Link URL.
Updated Inert YoutuneLink Modal dialog to set Title as required
=> FT2-310 Added code for Youtube url query params

DFC.ServiceTaxonomy.ContentApproval/DFC.ServiceTaxonomy.ContentApproval.csproj, DFC.ServiceTaxonomy.ContentApproval/Drivers/ContentApprovalPartDisplayDriver.cs, DFC.ServiceTaxonomy.ContentApproval/Manifest.cs
Guard clause added to ContentApprovalPartDisplayDriver to ensure not in Preview mode.
=> FT2 429 preview fix for content approval

DFC.ServiceTaxonomy.CustomEditor/Views/ContentsButtonEdit_SummaryAdmin.cshtml
Minor change to view/preview sharedcontent in new tab
=> Minor change to view/preview sharedcontent in new tab

DFC.ServiceTaxonomy.Editor/App_Data/Sites/Default/appsettings.template.json, DFC.ServiceTaxonomy.Editor/Recipes/00_Pages_SharedContent.recipe.json, DFC.ServiceTaxonomy.GraphSync/GraphSyncers/Exceptions/SetArgumentNullException.cs, DFC.ServiceTaxonomy.GraphSync/GraphSyncers/Helpers/SyncNameProvider.cs, DFC.ServiceTaxonomy.UnitTests/GraphSync/GraphSyncers/Helpers/SyncNameProviderHelperTests.cs
Release branch has been merged into master and this has now been merged back to dev to ensure continuity between dev and master.
=> Release1 1 4 1 merge

DFC.ServiceTaxonomy.Editor/Recipes/00_Pages_SharedContent.recipe.json, DFC.ServiceTaxonomy.Editor/Recipes/Forms Taxonomy .recipe.json, DFC.ServiceTaxonomy.Editor/Recipes/Home page - for environment import.recipe.json, DFC.ServiceTaxonomy.Editor/Recipes/Home page.recipe.json
Removal of content approvals from Home page content items
=> Fix for missing graph sync on text area widget

DFC.ServiceTaxonomy.Editor/Recipes/ERH - Page content type - for environment import.recipe.json, DFC.ServiceTaxonomy.Editor/Recipes/Page content type.recipe.json, DFC.ServiceTaxonomy.Editor/Recipes/Placements.recipe.json
Created Page content type recipe
Created   ERH environment recipe
=> Updated Placements for new Page field

DFC.ServiceTaxonomy.CustomEditor/Views/Content.SaveDraftButton.cshtml, DFC.ServiceTaxonomy.CustomEditor/Views/ContentPreview.Button.cshtml
Minor changes to the preview and save draft buttons to improve content editor experience
=> Amendments to preview and save draft buttons

Resources/AzureDevOps/VariableTemplates/SharedEnvironmentVariables.yml
Updated stax appsettings for Azure Ad Settings for Authority attribute
=> Minor change to update sharedvariable for stax appsettings

DFC.ServiceTaxonomy.Editor.sln, DFC.ServiceTaxonomy.Editor/DFC.ServiceTaxonomy.Editor.csproj, DFC.ServiceTaxonomy.Editor/Recipes/Service Taxonomy.recipe.json, DFC.ServiceTaxonomy.Editor/Recipes/Service Taxonomy2.recipe.json, DFC.ServiceTaxonomy.VersionComparison/Controllers/AdminController.cs, DFC.ServiceTaxonomy.VersionComparison/DFC.ServiceTaxonomy.VersionComparison.csproj, DFC.ServiceTaxonomy.VersionComparison/Drivers/VersionComparisonContentsDriver.cs, DFC.ServiceTaxonomy.VersionComparison/Drivers/VersionComparisonOptionsDisplayDriver.cs, DFC.ServiceTaxonomy.VersionComparison/Manifiest.cs, DFC.ServiceTaxonomy.VersionComparison/Models/VersionComparisonOptions.cs, DFC.ServiceTaxonomy.VersionComparison/Services/AuditTrailQueryService.cs, DFC.ServiceTaxonomy.VersionComparison/Services/IAuditTrailQueryService.cs, DFC.ServiceTaxonomy.VersionComparison/Startup.cs, DFC.ServiceTaxonomy.VersionComparison/ViewModels/VersionComparisonViewModel.cs, DFC.ServiceTaxonomy.VersionComparison/Views/Admin/Index.cshtml, DFC.ServiceTaxonomy.VersionComparison/Views/VersionComparison.cshtml, DFC.ServiceTaxonomy.VersionComparison/Views/VersionComparisonContentsAction_SummaryAdmin.cshtml, DFC.ServiceTaxonomy.VersionComparison/Views/VersionComparisonSelectLists.cshtml, DFC.ServiceTaxonomy.VersionComparison/Views/_ViewImports.cshtml
Added new version comparison module
Create new compare version admin page
Added version compare drop down list to select versions
Update recipes
Added Compare version link to manage content items page
=> FT2-293 version comparison base module and ddls

DFC.ServiceTaxonomy.VersionComparison/Services/DiffBuilderService.cs, DFC.ServiceTaxonomy.VersionComparison/Services/PropertyServices/AddBannerPropertyService.cs, DFC.ServiceTaxonomy.VersionComparison/Services/PropertyServices/PageLocationsPropertyService.cs, DFC.ServiceTaxonomy.VersionComparison/Views/Admin/Index.cshtml
Paragraph symbol removed from diff
Display text for fields used where possible
=> ft2-910 display text and symbol removal

DFC.ServiceTaxonomy.ContentPickerPreview/Services/BannerContentPickerResultProvider.cs
MInor code change to fix bug in Banner Content Picker. Banner content picker works only if  dropdown list itemtype is Banner.
=> Add code to fix bug in BannerContentPicker

DFC.ServiceTaxonomy.Editor/Recipes/237. JobProfileNew.recipe.json, DFC.ServiceTaxonomy.Editor/Recipes/Placements.recipe.json, DFC.ServiceTaxonomy.Editor/Recipes/Service Taxonomy.recipe.json
Files modified:
Placements.recipe.json
Service Taxonomy.recipe.json
New file created:
237. JobProfileNew.recipe.json
=> FT2-968: STAX CMS - Metadata tab in Job Profile

DFC.ServiceTaxonomy.Editor/Recipes/237. JobProfileNew.recipe.json, DFC.ServiceTaxonomy.Editor/Recipes/Service Taxonomy.recipe.json
JobProfileNew recipe.json and Service Taxonomy.recipe.json have been updated
=> FT2-971 fixed

DFC.ServiceTaxonomy.Editor/Recipes/237. JobProfileNew.recipe.json, DFC.ServiceTaxonomy.Editor/Recipes/Placements.recipe.json, DFC.ServiceTaxonomy.Editor/Recipes/Service Taxonomy.recipe.json
FT2-969: STAX CMS - Header tab in Job Profile
FT2-972: Alternative Title of Job Profile- CMS
FT2-974: Overview Field in Job Profile - CMS
=> FT2-969, FT2-972, FT2-974

DFC.ServiceTaxonomy.Editor/Recipes/237. JobProfile.recipe.json, DFC.ServiceTaxonomy.Editor/Recipes/Placements.recipe.json, DFC.ServiceTaxonomy.Editor/appsettings.Development_template.json, DFC.ServiceTaxonomy.JobProfiles.Module/Handlers/JobProfileContentHandler.cs, DFC.ServiceTaxonomy.JobProfiles.Module/Startup.cs
=> FT2-1127 job profiles skills automation

DFC.ServiceTaxonomy.CustomEditor/Views/TextField-PublishedReadOnly.Edit.cshtml, DFC.ServiceTaxonomy.CustomEditor/Views/TextField-PublishedReadOnly.Option.cshtml, DFC.ServiceTaxonomy.Editor/Recipes/260.JobProfileSOCcode.recipe.json, DFC.ServiceTaxonomy.Title/Drivers/UniqueTitlePartDisplayDriver.cs, DFC.ServiceTaxonomy.Title/Settings/UniqueTitlePartSettings.cs, DFC.ServiceTaxonomy.Title/Settings/UniqueTitlePartSettingsDisplayDriver.cs, DFC.ServiceTaxonomy.Title/Settings/UniqueTitlePartSettingsViewModel.cs, DFC.ServiceTaxonomy.Title/ViewModels/UniqueTitlePartViewModel.cs, DFC.ServiceTaxonomy.Title/Views/UniqueTitlePart.Edit.cshtml, DFC.ServiceTaxonomy.Title/Views/UniqueTitlePartSettings.Edit.cshtml, DFC.ServiceTaxonomy.Title/Views/UniqueTitlePartSettings.cshtml
=> FT2-1162 Read only when published fields

DFC.ServiceTaxonomy.ContentApproval/Services/ContentItemsApprovalService.cs, DFC.ServiceTaxonomy.ContentApproval/Views/ContentApprovalItemStatusDashboardPart_DetailAdmin.cshtml, DFC.ServiceTaxonomy.JobProfiles.Module/Migrations.cs
Fixing links on dashboard cards to work with new filters
Fixing publish count to exclude hidden content items
Fix for SQLLite in migrations
=> FT2-1196 Fixes for revised standard filters and the dashboard

DFC.ServiceTaxonomy.JobProfiles.Module/ServiceBusHandling/Converters/Helper.cs, DFC.ServiceTaxonomy.Taxonomies/Controllers/AdminController.cs, DFC.ServiceTaxonomy.Taxonomies/DFC.ServiceTaxonomy.Taxonomies.csproj
=> FT2-1215 breadcrumb fix

DFC.ServiceTaxonomy.Banners/DFC.ServiceTaxonomy.Banners.csproj, DFC.ServiceTaxonomy.CSharpScriptGlobals.CypherToContent/DFC.ServiceTaxonomy.CSharpScriptGlobals.CypherToContent.csproj, DFC.ServiceTaxonomy.Content/DFC.ServiceTaxonomy.Content.csproj, DFC.ServiceTaxonomy.ContentApproval/Controllers/ContentApprovalController.cs, DFC.ServiceTaxonomy.ContentApproval/DFC.ServiceTaxonomy.ContentApproval.csproj, DFC.ServiceTaxonomy.ContentApproval/Drivers/ContentApprovalPartDisplayDriver.cs, DFC.ServiceTaxonomy.ContentPickerPreview/DFC.ServiceTaxonomy.ContentPickerPreview.csproj, DFC.ServiceTaxonomy.CustomEditor/DFC.ServiceTaxonomy.CustomEditor.csproj, DFC.ServiceTaxonomy.CustomFields/DFC.ServiceTaxonomy.CustomFields.csproj, DFC.ServiceTaxonomy.Cypher/DFC.ServiceTaxonomy.Cypher.csproj, DFC.ServiceTaxonomy.DataAccess/DFC.ServiceTaxonomy.DataAccess.csproj, DFC.ServiceTaxonomy.Editor/DFC.ServiceTaxonomy.Editor.csproj, DFC.ServiceTaxonomy.Events/DFC.ServiceTaxonomy.Events.csproj, DFC.ServiceTaxonomy.GraphLookup/DFC.ServiceTaxonomy.GraphLookup.csproj, DFC.ServiceTaxonomy.GraphSync/DFC.ServiceTaxonomy.GraphSync.csproj, DFC.ServiceTaxonomy.GraphSync/Orchestrators/ContentTypeOrchestrator.cs, DFC.ServiceTaxonomy.GraphVisualiser/DFC.ServiceTaxonomy.GraphVisualiser.csproj, DFC.ServiceTaxonomy.JobProfiles.Module/DFC.ServiceTaxonomy.JobProfiles.Module.csproj, DFC.ServiceTaxonomy.JobProfiles.Module/Handlers/SocCodeContentHandler.cs, DFC.ServiceTaxonomy.PageLocation/DFC.ServiceTaxonomy.PageLocation.csproj, DFC.ServiceTaxonomy.PageLocation/Handlers/DefaultPageLocationsContentHandler.cs, DFC.ServiceTaxonomy.Taxonomies/Controllers/AdminController.cs, DFC.ServiceTaxonomy.Taxonomies/DFC.ServiceTaxonomy.Taxonomies.csproj, DFC.ServiceTaxonomy.Theme/DFC.ServiceTaxonomy.Theme.csproj, DFC.ServiceTaxonomy.Title/DFC.ServiceTaxonomy.Title.csproj, DFC.ServiceTaxonomy.UnpublishLater/DFC.ServiceTaxonomy.UnpublishLater.csproj, DFC.ServiceTaxonomy.VersionComparison/Controllers/AdminController.cs, DFC.ServiceTaxonomy.VersionComparison/DFC.ServiceTaxonomy.VersionComparison.csproj, GetJobProfiles/GetJobProfiles.csproj
This reverts commit 9da1cf20f8c9d63e127563748ebff7335e2b68f9.
=> Revert "Upgrade to OC 1.1 (#944)"

DFC.ServiceTaxonomy.GraphSync/CosmosDb/CosmosDbEndpoint.cs, DFC.ServiceTaxonomy.GraphSync/CosmosDb/CosmosDbService.cs, DFC.ServiceTaxonomy.GraphSync/CosmosDb/GraphSyncers/CosmosDbValidateAndRepairGraph.cs, DFC.ServiceTaxonomy.GraphSync/Extensions/JObjectExtensions.cs, DFC.ServiceTaxonomy.GraphSync/Extensions/UrlExtension.cs, DFC.ServiceTaxonomy.GraphSync/GraphSyncers/Fields/ContentPickerFieldGraphSyncer.cs, DFC.ServiceTaxonomy.GraphSync/GraphSyncers/Helpers/GraphValidationHelper.cs, DFC.ServiceTaxonomy.GraphSync/GraphSyncers/Parts/GraphSyncPartGraphSyncer.cs, DFC.ServiceTaxonomy.GraphSync/Helpers/DocumentHelper.cs, DFC.ServiceTaxonomy.GraphSync/JsonConverters/SubgraphConverter.cs, DFC.ServiceTaxonomy.GraphSync/Orchestrators/Orchestrator.cs, DFC.ServiceTaxonomy.GraphSync/Orchestrators/SyncOrchestrator.cs, DFC.ServiceTaxonomy.GraphSync/Startup.cs
- Fixes some more relationships issues
- Fix issue with repair graph sessions
- Stop users deleting content items that are in use
- Better error message when trying to delete a content item in use
- Fixed bug with container names
=> FT2-1452, FT2-1460, FT2-1461 - Maintain current behaviour when attempting to delete items that are in use by other items

DFC.ServiceTaxonomy.GraphSync/CosmosDb/CosmosDbDescribeContentItemHelper.cs, DFC.ServiceTaxonomy.GraphSync/CosmosDb/CosmosDbEndpoint.cs, DFC.ServiceTaxonomy.GraphSync/CosmosDb/CosmosDbService.cs, DFC.ServiceTaxonomy.GraphSync/CosmosDb/CosmosDbSubgraphQuery.cs, DFC.ServiceTaxonomy.GraphSync/CosmosDb/Queries/CosmosDbGetIncomingContentPickerRelationshipsQuery.cs, DFC.ServiceTaxonomy.GraphSync/CosmosDb/Queries/CosmosDbNodeAndNestedOutgoingRelationshipsQuery.cs, DFC.ServiceTaxonomy.GraphSync/CosmosDb/Queries/CosmosDbNodeAndOutRelationshipsAndTheirInRelationshipsQuery.cs, DFC.ServiceTaxonomy.GraphSync/GraphSyncers/VisualiseGraphSyncer.cs, DFC.ServiceTaxonomy.GraphSync/Helpers/ContentDefinitionHelper.cs, DFC.ServiceTaxonomy.GraphSync/Models/Query.cs
Also some refactoring and extra detail around a common error
=> FT2-1464 - Fixed some issues caused by parameterisation work

DFC.ServiceTaxonomy.Editor/Recipes/02_A_JobProfiles_ContentTypes.PublishUnpublishParts.recipe.json
Update 02_A_JobProfiles_ContentTypes.PublishUnpublishParts.recipe.json
=> Update description of 02_A_JobProfiles_ContentTypes.PublishUnpublishParts.recipe.json 

DFC.ServiceTaxonomy.Banners/Views/BannerPart.Edit.cshtml, DFC.ServiceTaxonomy.ContentApproval/Views/ContentApprovalPart.Admin.RequestReview.cshtml, DFC.ServiceTaxonomy.ContentApproval/Views/ContentApprovalPart.Edit.ForcePublish.cshtml, DFC.ServiceTaxonomy.ContentApproval/Views/ContentApprovalPart.Edit.RequestReview.cshtml, DFC.ServiceTaxonomy.ContentApproval/Views/ContentsMeta_SummaryAdmin.cshtml, DFC.ServiceTaxonomy.ContentApproval/Views/ContentsTags_SummaryAdmin.cshtml, DFC.ServiceTaxonomy.ContentApproval/Views/DashboardWidget.DetailAdmin.cshtml, DFC.ServiceTaxonomy.ContentPickerPreview/Views/ContentPickerField-Preview.Edit.cshtml, DFC.ServiceTaxonomy.CustomEditor/Views/Content.PublishButton.cshtml, DFC.ServiceTaxonomy.CustomEditor/Views/Content.SaveDraftButton.cshtml, DFC.ServiceTaxonomy.CustomEditor/Views/ContentEdit_AdditionalActions.cshtml, DFC.ServiceTaxonomy.CustomFields/Views/AccordionField.Edit.cshtml, DFC.ServiceTaxonomy.CustomFields/Views/TabField.Edit.cshtml, DFC.ServiceTaxonomy.GraphSync/Notifications/GraphSyncNotifier.cs, DFC.ServiceTaxonomy.GraphSync/Views/GraphSync/TriggerSyncValidation.cshtml
changed data-html, data-target, data-title and data-toggle in line with bootstrap5 changes
=> NCSLT-5215

DFC.ServiceTaxonomy.JobProfiles.DataTransfer/AzureSearch/Converters/JobProfileIndexMessageConverter.cs, DFC.ServiceTaxonomy.JobProfiles.DataTransfer/Models/AzureSearch/JobProfileIndex.cs
* NCSLT-5155 SOC fields in AzureSearch
* Updated JobProfile Search Index to also include Soc2020 fields
---------
=> Merge Release 38 to master

Resources/AzureDevOps/azure-pipelines.yml
This is aimed to fix the issue noticed with new Az Powershell module conflict with AzureRm modules.
=> Changed dfc-devops repo reference to point to latest tag.

DFC.ServiceTaxonomy.PageLocation/Constants/ContentTypes.cs, DFC.ServiceTaxonomy.PageLocation/Drivers/PageLocationPartDisplayDriver.cs, DFC.ServiceTaxonomy.PageLocation/Migrations.cs, DFC.ServiceTaxonomy.PageLocation/ViewModels/PageLocationPartViewModel.cs
Update Triage Tool to allow it to retrieve pre-existing data
=> Update TriageTool Test

DFC.ServiceTaxonomy.CompUi/DFC.ServiceTaxonomy.CompUi.csproj, DFC.ServiceTaxonomy.CompUi/Handlers/CacheHandler.cs, DFC.ServiceTaxonomy.Editor/DFC.ServiceTaxonomy.Editor.csproj, DFC.ServiceTaxonomy.JobProfiles.DataTransfer/DFC.ServiceTaxonomy.JobProfiles.DataTransfer.csproj, DFC.ServiceTaxonomy.JobProfiles.DataTransfer/GraphQL/JobProfileSimplificationInputObjectType.cs, DFC.ServiceTaxonomy.JobProfiles.DataTransfer/GraphQL/JobProfileSimplificationPartIndexAliasProvider.cs, DFC.ServiceTaxonomy.JobProfiles.DataTransfer/Migrations.cs, DFC.ServiceTaxonomy.JobProfiles.DataTransfer/Models/JobProfileSimplificationPart.cs, DFC.ServiceTaxonomy.JobProfiles.DataTransfer/Startup.cs, DFC.ServiceTaxonomy.PageLocation/Constants/ContentTypes.cs, DFC.ServiceTaxonomy.PageLocation/GraphQL/PageLocationInputObjectType.cs, DFC.ServiceTaxonomy.PageLocation/GraphQL/PageLocationPartQueryObjectType.cs, DFC.ServiceTaxonomy.PageLocation/Indexes/PageLocationPartIndex.cs, DFC.ServiceTaxonomy.PageLocation/Migrations.cs, DFC.ServiceTaxonomy.PageLocation/Models/PageLocationPart.cs
=> Code change to create the additional index required for PageLocation.

DFC.ServiceTaxonomy.CompUi/Handlers/CacheHandler.cs, DFC.ServiceTaxonomy.CompUi/Models/Page.cs
Added Page Api cache key invalidation
=> Added Page Api cache key invalidation

DFC.ServiceTaxonomy.CompUi/DFC.ServiceTaxonomy.CompUi.csproj, DFC.ServiceTaxonomy.CompUi/Enums/ContentTypes.cs, DFC.ServiceTaxonomy.CompUi/Enums/DraftContentTypes.cs, DFC.ServiceTaxonomy.CompUi/Handlers/CacheHandler.cs, DFC.ServiceTaxonomy.CompUi/Interfaces/ICacheHandler.cs, DFC.ServiceTaxonomy.Editor/DFC.ServiceTaxonomy.Editor.csproj
Now invalidating all DRAFT content types in addition to publish, delete and unpublish.
=> Now invalidating all content types in the enum list fo DRAFT.

DFC.ServiceTaxonomy.CompUi/DFC.ServiceTaxonomy.CompUi.csproj, DFC.ServiceTaxonomy.CompUi/Interfaces/IBuilder.cs, DFC.ServiceTaxonomy.CompUi/Services/ConcreteBuilder.cs, DFC.ServiceTaxonomy.CompUi/Services/Director.cs, DFC.ServiceTaxonomy.Editor/DFC.ServiceTaxonomy.Editor.csproj, DFC.ServiceTaxonomy.Editor/appsettings.json
https://skillsfundingagency.atlassian.net/wiki/spaces/DFC/pages/4318953473/Job+Profile+-+How+To+Become#GraphQL
=> AD-175407: Added invalidation for HowToBecome

DFC.ServiceTaxonomy.CompUi/Interfaces/IBuilder.cs, DFC.ServiceTaxonomy.CompUi/Services/ConcreteBuilder.cs
=> Added Job Profile API invalidation.

DFC.ServiceTaxonomy.CompUi/Handlers/CacheHandler.cs, DFC.ServiceTaxonomy.CompUi/Models/Processing.cs, DFC.ServiceTaxonomy.CompUi/Services/ConcreteBuilder.cs, DFC.ServiceTaxonomy.UnitTests/CompUi/CompuiHandlerTests.cs, DFC.ServiceTaxonomy.UnitTests/CompUi/TestData.cs, DFC.ServiceTaxonomy.UnitTests/ConcreteBuilder/ConcreteBuilderUnitTests.cs
Changes relating to URL updates.
=> Ss phase 1

Resources/ArmTemplates/parameters.json, Resources/ArmTemplates/template.json, Resources/ArmTemplates/test-parameters.json
=> Remove app service certificate deployment to unblock

DFC.ServiceTaxonomy.CustomEditor/Views/ContentEdit_AdditionalActions.cshtml, DFC.ServiceTaxonomy.CustomEditor/Views/ContentsButtonActions_SummaryAdmin.cshtml
=> Ssp2/us 196588/196589 remove buttons for header and footer

DFC.ServiceTaxonomy.CustomEditor/Views/ContentPreview.Button.cshtml, DFC.ServiceTaxonomy.Editor/appsettings.json, Resources/ArmTemplates/parameters.json, Resources/ArmTemplates/template.json, Resources/ArmTemplates/test-parameters.json, Resources/AzureDevOps/VariableTemplates/DevCloneEnvironmentVariables.yml, Resources/AzureDevOps/VariableTemplates/DevEnvironmentVariables.yml, Resources/AzureDevOps/VariableTemplates/LabEnvironmentVariables.yml, Resources/AzureDevOps/VariableTemplates/PPEnvironmentVariables.yml, Resources/AzureDevOps/VariableTemplates/PRDEnvironmentVariables.yml, Resources/AzureDevOps/VariableTemplates/SitCloneEnvironmentVariables.yml, Resources/AzureDevOps/VariableTemplates/SitEnvironmentVariables.yml
Updated preview functionality to use relative url for redirection + existing preview functionality for as-is not to use content main app call for token verification.
=> Release/system simplification/release 72.8

Resources/AzureDevOps/VariableTemplates/DevCloneEnvironmentVariables.yml, Resources/AzureDevOps/VariableTemplates/DevEnvironmentVariables.yml, Resources/AzureDevOps/VariableTemplates/LabEnvironmentVariables.yml, Resources/AzureDevOps/VariableTemplates/SitCloneEnvironmentVariables.yml, Resources/AzureDevOps/VariableTemplates/SitEnvironmentVariables.yml
ssp2 route suffix removed from the configuration for PROD release.
=> ssp2 prefix in the url route config removed.

DFC.ServiceTaxonomy.CompUi/Handlers/CacheHandler.cs
Added code to additionally refresh sector landing pages if a job profile is refreshed too.
=> Updated code to additionally refresh sector landing pages.

DFC.ServiceTaxonomy.Editor/Recipes/00_Pages_HelpPages.recipe.json
Remove recipe content that reference LMI
=> removed LMI references

DFC.ServiceTaxonomy.CompUi/Handlers/CacheHandler.cs, DFC.ServiceTaxonomy.Editor/Security/ApplicationBuilderExtensions.cs, DFC.ServiceTaxonomy.Theme/DFC.ServiceTaxonomy.Theme.csproj, Resources/ArmTemplates/parameters.json, Resources/ArmTemplates/template.json, Resources/ArmTemplates/test-parameters.json, Resources/AzureDevOps/VariableTemplates/DevCloneEnvironmentVariables.yml, Resources/AzureDevOps/VariableTemplates/DevEnvironmentVariables.yml, Resources/AzureDevOps/VariableTemplates/LabEnvironmentVariables.yml, Resources/AzureDevOps/VariableTemplates/PPEnvironmentVariables.yml, Resources/AzureDevOps/VariableTemplates/PRDEnvironmentVariables.yml, Resources/AzureDevOps/VariableTemplates/SitCloneEnvironmentVariables.yml, Resources/AzureDevOps/VariableTemplates/SitEnvironmentVariables.yml, Resources/AzureDevOps/azure-pipelines.yml
- NuGet Package upgraded from 0.1.4 to 0.3.1
- Removed Build Warning for null value
=> Upgrade NuGet Package to 0.3.1

DFC.ServiceTaxonomy.Theme/DFC.ServiceTaxonomy.Theme.csproj
Upgrade NuGet Package to v1.0.1 from v0.5.1
=> Upgrade NuGet Package to 1.0.1
